version: '3.8'

services:
  backend:
    build:
      context: ./backend
      target: development
    container_name: calendar-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./data/app.db
      - APP_ENV=development
      - TZ=UTC
      - BACKEND_HOST=0.0.0.0
      - BACKEND_PORT=8000
    volumes:
      - ./backend:/app
      - backend_data:/app/data
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/healthz')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      target: development
    container_name: calendar-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE=http://localhost:8000/api/v1
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - app-network

volumes:
  backend_data:
    driver: local

networks:
  app-network:
    driver: bridge