version: '3.8'

services:
  backend:
    build:
      context: ./backend
      target: production
    container_name: calendar-backend-prod
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./data/app.db
      - APP_ENV=production
      - TZ=UTC
      - BACKEND_HOST=0.0.0.0
      - BACKEND_PORT=8000
    volumes:
      - backend_data:/app/data
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/healthz')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      target: production
    container_name: calendar-frontend-prod
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped

volumes:
  backend_data:
    driver: local

networks:
  app-network:
    driver: bridge